
system_packages=(

    "xdg-desktop-portal"
    "libva-intel-driver"
    "libva-mesa-driver"
    "cups"
    "power-profiles-daemon"
    "system-config-printer"
    "cups-pk-helper"
    "paru"
    "appimagelauncher"
    "p7zip"
    "unrar"
    "npm"
    "wget"
    "gvfs"
    "zsh"
    "yt-dlp"
    "rsync"
    "hunspell-en_US"
    "ufw"
    "speech-dispatcher"
    "qt5-tools"
    "gtk4"
    "libdbusmenu-glib"
    "appmenu-gtk-module"
    "libappindicator-gtk3"
    "trash-cli"
    "dust"
    "neovim"
    "wl-clipboard"
    "gparted"
    "fzf"
    "jq"
    "zoxide"
    "fd"
    "papirus-icon-theme"
    "papirus-folders"
    "mkvtoolnix-gui"
    "bat"
    "bat-extras"
    "gum"
    "figlet"
    "rclone"
    "rclone-browser"
    "plymouth-theme-catppuccin-mocha-git"
)



aur_packages=(
    "archlinux-tweak-tool"
    "vorta-root"
    "ookla-speedtest-bin"
    "zed-git"
)
