
user_packages=(

    "syncthing"
    "ventoy-bin"
    "alacrity"
    "nwg-look"
    "webcord"
    "mpv"
    "vorta"
    "libreoffice-fresh"
    "gst-plugins-base-libs"
    "code"
    "code-marketplace"
    "code-features"
    "librewolf"
    "librewolf-extension-plasma-integration"
    "firefox-pwa"
    "obsidian"
    "brave-bin"
    "64gram-desktop"
    "yazi"
    "bottom"
    "obs-studio"
    "github-desktop"
    "keepassxc"
    "vorta"
    "gnome-disk-utility"
    "rofi-wayland"
    "lazygit"
)

