[mgr]

[prepend_keymap]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod selected files"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]
