
[manager]
show_hidden=true
sort_by="natural"
sort_dir_first=true
linemode="size"
show_symnlink=true


[opener]

edit = [
	{ run = 'nvim "$@"', block = true, desc = "NeoVim" },
	{ run = 'codium "$@"', block = true, desc = "VsCodium" },
	{ run = 'kate "$@"', block = true, desc = "kate" },
]

play = [
	{ run = 'mpv "$@"', orphan = true, desc = "MPV" },
	{ run = 'vlc "$@"', orphan = true, desc = "VLC"},
]

open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]

prepend_rules = [
  {name = "*.jsonc", use = "edit"},
]
