
[manager]
show_hidden=true
sort_by="natural"
sort_dir_first=true
linemode="size"
show_symnlink=true


[opener]

edit = [
	{ run = 'nvim "$@"', block = true, desc = "NeoVim" },
	{ run = 'code "$@"', block = true, desc = "VsCode" },
	{ run = 'codium "$@"', block = true, desc = "VsCodium" },
	{ run = 'pluma "$@"', block = true, desc = "Pluma" },
]

play = [
	{ run = 'mpv "$@"', orphan = true, desc = "MPV" },
	{ run = 'vlc "$@"', orphan = true, desc = "VLC"},
]

open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open" },
	{ run = 'olular "$@"', desc = "Okular" },
]

[add-sub]
run  = ''' echo sub-add "'$0'" | socat - /tmp/mpv.sock '''
desc = "Add sub to MPV"


[open]

prepend_rules = [
  {name = "*.jsonc", use = "edit"},
]

[prepend_rules]
name = "*.{ass,srt,ssa,sty,sup,vtt}"
use  = [ "add-sub", "edit" ]


