


[manager]
show_hidden=true
sort_by="natural"
sort_dir_first=true
linemode="size"
show_symnlink=true


[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "open in NeoVim" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]


