
rice_pckgs=(

    "ttf-hack-nerd"
    "ttf-noto-nerd"
    "ttf-firacode-nerd"
    "ttf-jetbrains-mono-nerd"

    "papirus-icon-theme"
    "papirus-folders-catppuccin-git"
    "catppuccin-cursors-frappe"
    "archlinux-tweak-tool-git"

    "fastfetch"
    "nwg-look"
    "plymouth-theme-catppuccin-mocha-git"
)


core_pckgs=(

    "intel-ucode"
    "libva-intel-driver"
    # "libva-mesa-driver"
    "upower"
    "fwupd"
    "fwupd-docs"
    "ufw"
    "xdg-desktop-portal"
    "gst-plugins-base"
    "gst-plugins-good"
    "gst-plugins-bad"
    "gst-libav"
    "cups"
    "paru"
    "power-profiles-daemon"
    "system-config-printer"
    "cups-pk-helper"
    "p7zip"
    "unrar"
    "npm"
    "icu"
    "wget"
    "gvfs"
    "zsh"
    "zsh-completions"
    "neovim"
    "yt-dlp"
    "rsync"
    "enchant"
    "hunspell-en_US"
    "speech-dispatcher"
    "qt5-tools"
    "gtk4"
    "libdbusmenu-glib"
    "appmenu-gtk-module"
    "libappindicator-gtk3"
    "trash-cli"
    "rclone"
    "python-pip"
    "flatpak"
    "flatpak-xdg-utils"
    "vorta"
    "vorta-root"
)


cli_pckgs=(

    "kitty"
    "neovim"
    "lsd"
    "bottom"
    "jq"
    "fd"
    "ripgrep"
    "chafa"
    "fzf"
    "ffmpegthumbnailer"
    "zoxide"
    "bat"
    "bat-extras"
    "yazi"
    "zathura"
    "zathura-pdf-poppler"
    "zathura-cb"
    "syncthing"
    "gum"
    "figlet"
    "rclone"
    "v4l2loopback-dkms"
    "wl-clipboard"
    "dust"
    "yt-dlp"
    "lazygit"
    "ookla-speedtest-bin"
)


de_pckgs=(

    "xdg-desktop-portal-kde"
    # "xdg-desktop-portal-hyprland"
    "flatpak-kcm"
    "kate"
    "kup"
    "kimageformats"
    "ark"
    "kio-admin"
    "packagekit-qt6"
    "kdialog"
    "kasts"
    "spectacle"
    "ktorrent"
    "gwenview"
    "okular"
    "kcalc"
    "kdeconnect"
    "dolphin-plugins"
    "kdeconnect"
    "kdeplasma-addons"
    "kwin-scripts-krohnkite-git"
    "kwin-effect-rounded-corners-git"
    "plasma-browser-integration"
    "rofi-wayland"
)



user_pckgs=(

    "code"
    "code-marketplace"
    "code-features"
    "github-desktop"
    "mpv"
    "vlc"
    "obsidian"
    "librewolf"
    "librewolf-firefox-shim"
    "librewolf-extension-plasma-integration"
    "firefox-pwa"
    "brave-bin"
    "webcord"
    "64gram-desktop"
    "keepassxc"

    "gnome-disk-utility"
    "rclone-browser"
    "mkvtoolnix-gui"
    "gparted"
    "libreoffice-fresh"
    "appimagelauncher"
    "obs-studio"
    "v4l2loopback-dkms"
    "ventoy-bin"
)

