// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "6ee3b317-4b65-472f-87eb-81aca2c6fdc8");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"on Windows but cannot usually use BITS\",\"the maintenance service registry key is not present\"]");
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.F0DC299D809B9700", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1728536066);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 149);
user_pref("browser.newtabpage.activity-stream.impressionId", "{851f2d95-9c9d-4ac7-b31b-27faf9117bfb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1728536068);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1728536084523");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1728557684523");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1728536068");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240930174542");
user_pref("browser.startup.homepage_override.mstone", "130.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1728536068);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"wrapper-sidebar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"zen-sidebar-top-buttons\":[\"preferences-button\",\"zen-expand-sidebar-button\",\"zen-profile-button\"],\"zen-sidebar-icons-wrapper\":[\"zen-sidepanel-button\",\"zen-workspaces-button\",\"new-tab-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"zen-sidebar-icons-wrapper\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.iniFile.exists.appversion", "1.0.1-a.7");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "51cf039cc8684cdc8e4671b13e776e3b");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECN6XHkiUPoNdBAhNwfNd23J+jA==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240930174542");
user_pref("extensions.lastAppVersion", "1.0.1-a.7");
user_pref("extensions.lastPlatformVersion", "130.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9826bb9f-7434-4aaf-8661-640587eaa365\",\"pictureinpicture@mozilla.org\":\"0cd006af-fe45-4cd9-9b3e-f0d6d9fb9271\",\"screenshots@mozilla.org\":\"ee0be3ef-b88d-4edd-8de7-d9fa52ec7022\",\"webcompat-reporter@mozilla.org\":\"bb56a14c-0589-4c80-aaab-306dfe235502\",\"webcompat@mozilla.org\":\"c40072fa-a753-484e-bbfc-1c49f8b118c6\",\"firefox-compact-dark@mozilla.org\":\"06689c52-fc1c-46a7-9831-d4332a5eb53e\",\"addons-search-detection@mozilla.com\":\"05189bef-d0c4-4801-a2fe-8a11e95c493b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20240930174542");
user_pref("gfx-shader-check.device-id", "0x4626");
user_pref("gfx-shader-check.driver-version", "31.0.101.4502");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x4626");
user_pref("sanity-test.driver-version", "31.0.101.4502");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20240930174542");
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECKvi6HQXC87vBAh9PkrX95PY3Q==");
user_pref("toolkit.startup.last_success", 1728536065);
user_pref("toolkit.telemetry.cachedClientID", "79317eb9-f492-41ee-a693-2a2f54326a4a");
user_pref("toolkit.telemetry.cachedProfileGroupID", "5208e6dd-d35b-4e31-a692-901cfdcd119b");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("zen.keyboard.shortcuts.version", 1);
user_pref("zen.welcomeScreen.seen", true);
