
import = ["~/.config/alacritty/themes/themes/nord.toml"]
live_config_reload = true


[env]
TERM = "xterm-256color"


[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.95
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
padding = {x = 0, y = 0}


[font]
size = 9.8
normal =      {family = "JetBrainsMono Nerd Font", style = "Medium"}
bold =        {family = "JetBrainsMono Nerd Font", style = "Heavy"}
italic =      {family = "JetBrainsMono Nerd Font", style = "Medium Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Heavy Italic"}


[scrolling]
history = 100000
multiplier = 3


[mouse]
hide_when_typing = true
# bindings = [
# { mouse = "Right", mods = "Control", action = "Paste"},
# ]


[keyboard]
bindings = [
{ key = "Q", mods = "Control", action = "Quit"},
# { key = "L", mods = "Control", chars = "\f" },
{ mods = "Control|Shift", key = "C", action = "CopySelection" },
{ mods = "Control|Shift", key = "V", action = "PasteSelection" },
{ mods = "Control|Shift", key = "N",  action = "CreateNewWindow" },
]





